### ISSUE TITLE
最新版so包没上传呀

### ISSUE THREAD

**Issue by shisp** [tpnet/Libgdx-Backend-TextureView-Android#1]
最新版so包没上传呀1.9.14

**Comment by tpnet** [comment]
已经在gradle里面引入了。

**Comment by shisp** [comment]
2022-12-30 16:00:05.335 9703-9703/vip.skyhand.libgdxtextureview E/AndroidRuntime: FATAL EXCEPTION: main
    Process: vip.skyhand.libgdxtextureview, PID: 9703
    java.lang.ExceptionInInitializerError
        at vip.skyhand.libgdxtextureview.MainActivity$initListener$1.onClick(MainActivity.kt:26)
        at android.view.View.performClick(View.java:7252)
        at android.view.View.performClickInternal(View.java:7229)
        at android.view.View.access$3500(View.java:821)
        at android.view.View$PerformClick.run(View.java:27765)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:120)
        at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:31)
        at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(AndroidApplication.java:44)
        at vip.skyhand.libgdxtextureview.MainActivity$initListener$1.onClick(MainActivity.kt:26) 
        at android.view.View.performClick(View.java:7252) 
        at android.view.View.performClickInternal(View.java:7229) 
        at android.view.View.access$3500(View.java:821) 
        at android.view.View$PerformClick.run(View.java:27765) 
        at android.os.Handler.handleCallback(Handler.java:914) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7560) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/vip.skyhand.libgdxtextureview-qbmnS4E1mWpT0Iqr0lmXRw==/base.apk"],nativeLibraryDirectories=[/data/app/vip.skyhand.libgdxtextureview-qbmnS4E1mWpT0Iqr0lmXRw==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libgdx.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:114)
        at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:31) 
        at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(AndroidApplication.java:44) 
        at vip.skyhand.libgdxtextureview.MainActivity$initListener$1.onClick(MainActivity.kt:26) 
        at android.view.View.performClick(View.java:7252) 
        at android.view.View.performClickInternal(View.java:7229) 
        at android.view.View.access$3500(View.java:821) 
        at android.view.View$PerformClick.run(View.java:27765) 
        at android.os.Handler.handleCallback(Handler.java:914) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7560) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
